update tests

diff --git a/tests/test b/tests/test
--- a/tests/test
+++ b/tests/test
@@ -4,11 +4,14 @@ bin="./pipex"
 infile="${PWD}/README.md"
 expected_outfile="${PWD}/tests/expected_outfile"
 outfile="${PWD}/tests/outfile"
+NOPER="tests/nopermission"
+touch $NOPER
+chmod 0000 $NOPER
 
 NC="\033[0m"
 CYAN="\033[36m"
 RED="\033[31m"
-GREEN="\033[32m"
+GREEN="$(tput setaf 2)"
 YELLOW="\033[33m"
 
 print_title() {
@@ -103,19 +106,19 @@ run_test
 print_title "test8"
 print_test "test: < infile sleep 3 | cat -e -n > nopermission"
 # cleanup
-time $bin $infile "sleep 3" "cat -e -n" "outfiles/outfile_without_permissions"
-echo "actual exit code: $?"
-time < $infile sleep 3 | cat -e -n > "outfiles/outfile_without_permissions"
-echo "expected exit code: $?"
-run_test
+# time $bin $infile "sleep 3" "cat -e -n" "outfiles/outfile_without_permissions"
+# echo "actual exit code: $?"
+# time < $infile sleep 3 | cat -e -n > "outfiles/outfile_without_permissions"
+# echo "expected exit code: $?"
+# run_test
 
 #test 9
 print_title "test9"
 print_test "test: < infile badcommand | cat -e -n > nopermission"
 # cleanup
-$bin $infile "badcommand" "cat -e -n" "outfiles/outfile_without_permissions"
+$bin $infile "badcommand" "cat -e -n" $NOPER
 echo "actual exit code: $?"
-< $infile badcommand | cat -e -n > "outfiles/outfile_without_permissions"
+< $infile badcommand | cat -e -n > $NOPER
 echo "expected exit code: $?"
 run_test
 
@@ -126,5 +129,14 @@ print_test "test: < infile cat -e -n | badcommand  > outfile"
 $bin $infile "cat -e -n" "badcommand" $outfile
 echo "actual exit code: $?"
 < $infile cat -e -n | badcommand > $outfile
+echo "expected exit code: $?"
+run_test
+
+#test 11
+print_title "test11"
+print_test "test: < nopermission cat -e -n | badcommand  > outfile"
+$bin $NOPER "cat -e -n" "badcommand" $outfile
+echo "actual exit code: $?"
+< $NOPER cat -e -n | badcommand > $outfile
 echo "expected exit code: $?"
 run_test
