feat: fix leaks and norm

diff --git a/tests/test b/tests/test
--- a/tests/test
+++ b/tests/test
@@ -101,11 +101,11 @@ run_test
 print_title "test8"
 print_test "test: < infile sleep 3 | cat -e -n > nopermission"
 # cleanup
-time $bin $infile "sleep 3" "cat -e -n" "outfiles/outfile_without_permissions"
-echo "actual exit code: $?"
-time < $infile sleep 3 | cat -e -n > "outfiles/outfile_without_permissions"
-echo "expected exit code: $?"
-run_test
+# time $bin $infile "sleep 3" "cat -e -n" "outfiles/outfile_without_permissions"
+# echo "actual exit code: $?"
+# time < $infile sleep 3 | cat -e -n > "outfiles/outfile_without_permissions"
+# echo "expected exit code: $?"
+# run_test
 
 #test 9
 print_title "test9"
@@ -114,5 +114,15 @@ print_test "test: < infile badcommand | cat -e -n > nopermission"
 $bin $infile "badcommand" "cat -e -n" "outfiles/outfile_without_permissions"
 echo "actual exit code: $?"
 < $infile badcommand | cat -e -n > "outfiles/outfile_without_permissions"
+echo "expected exit code: $?"
+run_test
+
+#test 10
+print_title "test10"
+print_test "test: < infile cat -e -n | badcommand  > outfile"
+# cleanup
+valgrind --leak-check=full --track-fds=yes $bin $infile "cat -e -n" "badcommand" $outfile
+echo "actual exit code: $?"
+< $infile cat -e -n | badcommand > $outfile
 echo "expected exit code: $?"
 run_test
