wip still need to fix bug when binary not found

diff --git a/tests/test b/tests/test
--- a/tests/test
+++ b/tests/test
@@ -88,3 +88,31 @@ cleanup
 < $infile ls -l -a -f | cat -e -n > $expected_outfile
 $bin $infile "ls -l -a -f" "cat -e -n" $outfile
 run_test
+
+#test 7
+print_title "test7"
+print_test "test: < nonexisting ls -l -a -f | cat -e -n > outfile"
+cleanup
+< "nonexist" ls -l -a -f | cat -e -n > $expected_outfile
+$bin "nonexist" "ls -l -a -f" "cat -e -n" $outfile
+run_test
+
+#test 8
+print_title "test8"
+print_test "test: < infile sleep 3 | cat -e -n > nopermission"
+# cleanup
+time $bin $infile "sleep 3" "cat -e -n" "outfiles/outfile_without_permissions"
+echo "actual exit code: $?"
+time < $infile sleep 3 | cat -e -n > "outfiles/outfile_without_permissions"
+echo "expected exit code: $?"
+run_test
+
+#test 9
+print_title "test9"
+print_test "test: < infile badcommand | cat -e -n > nopermission"
+# cleanup
+$bin $infile "badcommand" "cat -e -n" "outfiles/outfile_without_permissions"
+echo "actual exit code: $?"
+< $infile badcommand | cat -e -n > "outfiles/outfile_without_permissions"
+echo "expected exit code: $?"
+run_test
